# commit to be tagged for new release
commit = "HEAD"

project_name = "CAPI Bootstrap Provider Talos"
github_repo = "talos-systems/cluster-api-bootstrap-provider-talos"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.3.0"

pre_release = true

preface = """\
"""

[notes]

    [notes.capi]
        title = "CAPI v1alpha4"
        description = """\
CABPT now supports CAPI v1alpha4.
"""
